### ISSUE TITLE
[mq|depends/conf/mqtt]High cpu usage caused by Mqtt message handling

### ISSUE THREAD

**Issue by CoderZhi** [machinefi/w3bstream#209]
----------------------------------------------------------+-------------
      flat  flat%   sum%        cum   cum%   calls calls% + context              
----------------------------------------------------------+-------------
                                             4.29s 57.58% |   runtime.checkTimers (inline)
                                             0.74s  9.93% |   runtime.casgstatus (inline)
                                             0.67s  8.99% |   github.com/eclipse/paho%2emqtt%2egolang.(*client).Subscribe
                                             0.59s  7.92% |   runtime.pidleget (inline)
                                             0.57s  7.65% |   github.com/eclipse/paho%2emqtt%2egolang.(*baseToken).WaitTimeout
                                             0.54s  7.25% |   runtime.findRunnable (inline)
     7.45s 35.12% 35.12%      7.45s 35.12%                | runtime.nanotime
----------------------------------------------------------+-------------
                                             4.88s   100% |   syscall.RawSyscall6
     4.88s 23.01% 58.13%      4.88s 23.01%                | runtime/internal/syscall.Syscall6
----------------------------------------------------------+-------------
                                             1.11s 38.01% |   github.com/eclipse/paho%2emqtt%2egolang.(*client).UpdateLastReceived
                                                1s 34.25% |   runtime.runtimer
                                             0.80s 27.40% |   github.com/eclipse/paho%2emqtt%2egolang.(*client).UpdateLastSent
     2.92s 13.77% 71.90%      2.92s 13.77%                | time.Now
----------------------------------------------------------+-------------
                                             0.89s 72.95% |   runtime.futexwakeup
                                             0.33s 27.05% |   runtime.futexsleep
     1.22s  5.75% 77.65%      1.22s  5.75%                | runtime.futex
----------------------------------------------------------+-------------
                                             1.16s   100% |   runtime.netpoll
     1.16s  5.47% 83.12%      1.16s  5.47%                | runtime.epollwait
----------------------------------------------------------+-------------
                                             0.40s   100% |   runtime.runqgrab
     0.40s  1.89% 85.01%      0.40s  1.89%                | runtime.usleep
----------------------------------------------------------+-------------
                                             0.36s 59.02% |   runtime.newobject
                                             0.05s  8.20% |   github.com/eclipse/paho%2emqtt%2egolang.(*client).Subscribe
                                             0.05s  8.20% |   github.com/eclipse/paho%2emqtt%2egolang.(*client).UpdateLastReceived
                                             0.03s  4.92% |   github.com/eclipse/paho.mqtt.golang/packets.(*SubscribePacket).String
                                             0.03s  4.92% |   github.com/eclipse/paho.mqtt.golang/packets.(*SubscribePacket).Write
                                             0.03s  4.92% |   github.com/eclipse/paho.mqtt.golang/packets.ReadPacket
     0.18s  0.85% 85.86%      0.61s  2.88%                | runtime.mallocgc
                                             0.16s 26.23% |   runtime.heapBitsSetType
                                             0.10s 16.39% |   runtime.memclrNoHeapPointers

**Comment by saitofun** [comment]
yes, subscribe func should be assigned once when channel create.
