### ISSUE TITLE
let's merge `getDB` and `getRedisDB`. leave the choice of using memory or redis to `project`

### ISSUE THREAD

**Issue by CoderZhi** [machinefi/w3bstream#231]
let's merge `getDB` and `getRedisDB`. leave the choice of using memory or redis to `project`

_Originally posted by @CoderZhi in https://github.com/machinefi/w3bstream/issues/228#issuecomment-1329507476_

**Comment by Liuhaai** [comment]
replace `ws_get_db`, `ws_set_db`, `ws_get_redis_db`, `ws_set_redis_db` with  `ws_get_kv_db`, `ws_set_kv_db`
